---

- name: Pause before export keys file
  pause:
    minutes: 2

- name: check vault status
  community.docker.docker_container_exec:
    container: "{{ vault_docker_container_name }}"
    command: "vault status"
  register: result

- name: Print vault status
  debug:
    var: result.stdout