---

- name: deploy vault
  docker_container:
    name: "{{ vault_docker_container_name }}"
    image: "{{ vault_docker_image }}"
    restart_policy: always
    capabilities:
      - IPC_LOCK
    ports:
      - "{{ vault_docker_ext_port }}:{{ vault_docker_int_port }}"
    volumes:
      - "{{ vault_docker_config_dir }}/config.hcl:/vault/config/config.hcl"
      - "{{ vault_docker_data_vol }}:/vault/file/"
    env:
      VAULT_ADDR: "http://127.0.0.1:{{ vault_docker_ext_port }}"
    command: server
    networks:
      - name: "{{ vault_docker_networks }}"
