---
- name: ensure prerequired software installed
  apt:
    update_cache: yes
    name:
      - 'ca-certificates'
      - 'gnupg'
      - 'lsb-release'

- name: install repo for docker
  block:
    - name: docker apt key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        keyring: "/etc/apt/trusted.gpg.d/docker.gpg"
        state: present
    - name: gitlab repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

- name: ensure required software installed
  apt:
    update_cache: yes
    name:
      - 'docker-ce'
      - 'docker-ce-cli'
      - 'containerd.io'
      - 'docker-compose-plugin'